Explicit fcl for offspill trig hit reco
Mu2e/mu2e_trig_config pull request #47
Opened 2024-12-12 23:22 UTC by bonventre

2024-12-13 23:45 UTC, brownd1978 approved these changes

2024-12-27 17:35 UTC, gianipez commented on core/producers/trigTrkProducers.fcl
> +      @table::TrkHitReco.producers.makeSH
would it make sense to `@table:...` the `TTmakeSHFromDigi` module instance?

2024-12-27 18:06 UTC, gianipez requested changes
Can you please confirm that the trigger fcl(s) runs with no problems? Also, I'd like to understand if the small changes I asked/commented-on can be made. 

Thanks, Giani

2025-01-08 14:02 UTC, gianipez approved these changes

2025-01-10 18:52 UTC, merged